language: node_js

env:
  global:
    - YARN_VERSION="1.21.1"

node_js:
  - "10.16"
  - "12.11"
  - "13.0"
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn lint
  - yarn test

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - node_modules
