name: Node CI

on:
  # Trigger the workflow manually via the GitHub UI
  workflow_dispatch:
  # Trigger the workflow when a pull_request's activity type is opened,
  # synchronize, or reopened.
  pull_request:
  # Trigger the workflow on push
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run:
          yarn --prefer-offline --frozen-lockfile --no-progress --silent
          --ignore-engines

      - run: yarn lint
      - run: yarn test
